### ISSUE TITLE
Reporte Práctica final

### ISSUE THREAD

**Issue by Lissete7** [SistemasTecTlaxiaco/practica-final-de-hilos-equipoxd#2]
[Practica Final (Hilos) u3.pdf](https://github.com/SistemasTecTlaxiaco/practica-final-de-hilos-equipoxd/files/6516565/Practica.Final.Hilos.u3.pdf)

**Comment by Edwin38H** [comment]
cal: 18

**Comment by josealfredo79** [comment]
Revisado y bien hecho
